### PR TITLE
feat(event): add genesis event

### PR DESCRIPTION
**Pull request by oetyng**
BREAKING CHANGE: Adds new event.

### CODE REVIEW

**Comment by dirvine** [comment]
This would not be a breaking change if that enum was declared as #[non_exhustive]

**Comment by dirvine** [comment]
Can you check @oetyng  if this is still required?

**Comment by oetyng** [comment]
> Can you check @oetyng if this is still required?

It's not a very important PR, but would be a bit cleaner with this.

**Comment by oetyng** [comment]
> This would not be a breaking change if that enum was declared as #[non_exhaustive]

Guys mostly in routing didn't want wildcard enum matchings before, so probably don't want to introduce it for this.

**Comment by oetyng** [comment]
Fork branch was overwritten.

**Pull request closed without merging**
